---
# tasks file for rcollins.php
- name: Reporting Start Task
  slack:
          token: "{{ token }}"
          msg: 'PHP install started'
          color: warning
          username: '{{ ansible_hostname }}'

- name: Add PPA to Apt
  apt_repository:
          repo: 'ppa:ondrej/php'

- name: Update Apt Cache
  apt:
          update_cache: yes
          cache_valid_time: 3600

- name: Install PHP Packages
  apt:
          name: "{{item}}"
          state: present
  with_items:
          - php
          - php-fpm
          - php-mysql
          - php-xml

- name: Remove Apache2 Install
  apt:
          name: apache2
          state: absent

- name: Reportng Finish Role
  slack:
          token: "{{ token }}"
          msg: ' PHP install completed'
          color: good
          username: ' {{ansible_hostname}} '
